version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.node
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.react
    ports:
      - "3000:80"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
