name: CD Pipeline
on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ---- Backend ----
      - name: Build backend image
        run: |
          docker build \
            -f Dockerfile.node \
            -t ${{ secrets.DOCKER_USERNAME }}/knovator-backend:latest \
            .

      - name: Push backend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/knovator-backend:latest

      # ---- Frontend ----
      - name: Build frontend image
        run: |
          docker build \
            -f Dockerfile.react \
            -t ${{ secrets.DOCKER_USERNAME }}/knovator-frontend:latest \
            .

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/knovator-frontend:latest
