# ---- Backend ----
- name: Build backend image
  run: |
    docker build \
      -f Dockerfile.node \
      -t ${{ secrets.DOCKER_USERNAME }}/knovator-backend:latest \
      ./backend

- name: Push backend image
  run: docker push ${{ secrets.DOCKER_USERNAME }}/knovator-backend:latest

# ---- Frontend ----
- name: Build frontend image
  run: |
    docker build \
      -f Dockerfile.react \
      -t ${{ secrets.DOCKER_USERNAME }}/knovator-frontend:latest \
      ./frontend

- name: Push frontend image
  run: docker push ${{ secrets.DOCKER_USERNAME }}/knovator-frontend:latest
